import { apiFetch } from "./api.js";
let charts = {}, currentUser = null;
function formatCurrency(value) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(value || 0); }
function safeExtract(obj, path, def = 0) { if (!obj || typeof obj !== 'object') return def; let val = obj; for (const key of path.split('.')) val = val?.[key]; return val ?? def; }
async function loadUserData() { let user = JSON.parse(localStorage.getItem("user")); if (!user) { window.location.href = "/index.html"; return null; } if (!user.financials || Object.keys(user.financials).length === 0) { try { const response = await apiFetch('/api/init-test-data/' + user.email, { method: "POST" }); user = response.user; localStorage.setItem("user", JSON.stringify(user)); } catch (err) { } } currentUser = user; return user; }
function populateMetrics(user) { const income = safeExtract(user, 'financials.monthly-income', 0), expenses = safeExtract(user, 'financials.monthly-expenses', 0), debt = safeExtract(user, 'financials.debt', 0), savings = Math.max(0, income - expenses); document.getElementById('metric-income').textContent = formatCurrency(income); document.getElementById('metric-expense').textContent = formatCurrency(expenses); document.getElementById('metric-savings').textContent = formatCurrency(savings); document.getElementById('metric-debt').textContent = formatCurrency(debt); return { income, expenses, debt, savings }; }
function populateProfile(user) { const name = user.Name || 'User', age = user.Age || '-', employment = user['employment-status'] || 'Not Specified'; document.getElementById('user-name').textContent = name; document.getElementById('user-email').textContent = user.email || 'user@example.com'; if (document.getElementById('profile-name')) document.getElementById('profile-name').textContent = name; if (document.getElementById('profile-age')) document.getElementById('profile-age').textContent = age; if (document.getElementById('profile-status')) document.getElementById('profile-status').textContent = employment; }
async function populateGoalData(user) { try { const response = await apiFetch('/api/goal-intelligence/' + user.email), goalData = response.goal_intelligence || {}; if (goalData.error) return; const targetAmount = safeExtract(goalData, 'target_amount', 0), expectedCorpus = safeExtract(goalData, 'expected_corpus', 0), probability = safeExtract(goalData, 'goal_probability', 0); if (document.getElementById('goal-target')) document.getElementById('goal-target').textContent = formatCurrency(targetAmount); if (document.getElementById('goal-corpus')) document.getElementById('goal-corpus').textContent = formatCurrency(expectedCorpus); if (document.getElementById('goal-prob')) document.getElementById('goal-prob').textContent = probability + '%'; } catch (err) { } }
function createIncomeExpenseChart(income, expenses) { const ctx = document.getElementById('incomeExpenseChart'); if (!ctx) return; if (charts.incomeExpense) charts.incomeExpense.destroy(); charts.incomeExpense = new Chart(ctx, { type: 'bar', data: { labels: ['Monthly'], datasets: [{ label: 'Income', data: [income], backgroundColor: '#10b981', borderRadius: 8 }, { label: 'Expenses', data: [expenses], backgroundColor: '#ef4444', borderRadius: 8 }] }, options: { responsive: true, maintainAspectRatio: true, scales: { y: { beginAtZero: true } } } }); }
function createHealthScoreChart(analytics) { const ctx = document.getElementById('healthScoreChart'); if (!ctx) return; if (charts.healthScore) charts.healthScore.destroy(); const score = 60; charts.healthScore = new Chart(ctx, { type: 'doughnut', data: { labels: ['Score', 'Remaining'], datasets: [{ data: [score, 100 - score], backgroundColor: ['#10b981', '#e5e7eb'], borderWidth: 0 }] }, options: { responsive: true, maintainAspectRatio: true, plugins: { legend: { display: false } } } }); }
function createExpenseBreakdownChart() { const ctx = document.getElementById('expenseBreakdownChart'); if (!ctx) return; if (charts.expenseBreakdown) charts.expenseBreakdown.destroy(); charts.expenseBreakdown = new Chart(ctx, { type: 'pie', data: { labels: ['Fixed', 'Variable', 'Discretionary'], datasets: [{ data: [60, 30, 10], backgroundColor: ['#4f46e5', '#7c3aed', '#f59e0b'], borderWidth: 0 }] }, options: { responsive: true, maintainAspectRatio: true, plugins: { legend: { position: 'bottom' } } } }); }
function createSavingsRatioChart(analytics) { const ctx = document.getElementById('savingsRatioChart'); if (!ctx) return; if (charts.savingsRatio) charts.savingsRatio.destroy(); charts.savingsRatio = new Chart(ctx, { type: 'line', data: { labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'], datasets: [{ label: 'Ratio %', data: [18, 19, 20, 21, 19, 22], borderColor: '#10b981', backgroundColor: 'rgba(16, 185, 129, 0.1)', borderWidth: 3, fill: true }] }, options: { responsive: true, maintainAspectRatio: true, scales: { y: { beginAtZero: true, max: 100 } } } }); }
async function loadAnalytics(user) { try { const response = await apiFetch('/api/analytics/' + user.email); createExpenseBreakdownChart(); createSavingsRatioChart(response.analytics || {}); createHealthScoreChart(response.analytics || {}); } catch (err) { } }
async function loadInsights(user) { try { const container = document.getElementById('insights-container'); if (!container) return; renderInsights([]); } catch (err) { } }
function renderInsights(insights) { }
window.logout = () => { if (confirm('Logout?')) { localStorage.removeItem('user'); localStorage.removeItem('onboardingCompleted'); window.location.href = '/index.html'; } };
document.addEventListener('DOMContentLoaded', async () => { try { const user = await loadUserData(); if (!user) return; const financials = populateMetrics(user); populateProfile(user); await populateGoalData(user); createIncomeExpenseChart(financials.income, financials.expenses); await loadInsights(user); document.getElementById('btn-refresh')?.addEventListener('click', () => window.location.reload()); console.log('✅ Dashboard Ready'); } catch (err) { console.error('Error:', err); } });
